// This file was auto-generated by prisma-generator-typescript-interfaces

export interface Symptom {
  id: number;
  name: string;
  category: string;
  importanceScore: number;
  source: string;
  correlations?: SymptomDiabetesCorrelation[];
  ruleConditions?: RuleCondition[];
  DiagnosisHistorySymptom?: DiagnosisHistorySymptom[];
  createdAt: Date;
  updatedAt: Date | null;
}

export interface DiabetesType {
  id: number;
  name: string;
  correlations?: SymptomDiabetesCorrelation[];
  createdAt: Date;
  updatedAt: Date | null;
}

export interface SymptomDiabetesCorrelation {
  id: number;
  symptomId: number;
  diabetesTypeId: number;
  symptom?: Symptom;
  diabetesType?: DiabetesType;
  createdAt: Date;
  updatedAt: Date | null;
}

export interface DiagnosisRule {
  id: number;
  ruleDescription: string;
  outputDiagnosis: string;
  ruleConditions?: RuleCondition[];
  createdAt: Date;
  updatedAt: Date | null;
}

export interface RuleCondition {
  id: number;
  ruleId: number;
  symptomId: number;
  rule?: DiagnosisRule;
  symptom?: Symptom;
  createdAt: Date;
  updatedAt: Date | null;
}

export interface DiagnosisHistory {
  id: number;
  userId: string;
  diagnosis: string;
  probability: string;
  createdAt: Date;
  symptoms?: DiagnosisHistorySymptom[];
}

export interface DiagnosisHistorySymptom {
  id: number;
  historyId: number;
  symptomId: number;
  history?: DiagnosisHistory;
  symptom?: Symptom;
}
